blueprint:
  name: Virtual device tracker
  description: >
    Updates a virtual device_tracker from any entity attribute that returns
    [latitude, longitude] (e.g., 'location')
  domain: automation
  input:
    geocoded_sensor:
      name: Geocoded location entity
      description: Entity with an attribute that returns [lat, lon]
      selector:
        entity: {}
    location_attribute:
      name: Attribute name
      description: Attribute holding [lat, lon]
      default: location
      selector:
        text:
    device_id:
      name: Device tracker ID (dev_id)
      description: device_tracker.<dev_id> will be created/updated
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input geocoded_sensor
    attribute: !input location_attribute

variables:
  eid: !input geocoded_sensor
  attr: !input location_attribute
  coords: "{{ state_attr(eid, attr) }}"

condition:
  - condition: template
    value_template: "{{ coords is not none }}"

action:
  - service: device_tracker.see
    data:
      dev_id: !input device_id
      gps: "{{ coords }}"
      attributes:
        source_type: gps
